### ISSUE TITLE
Так, сейчас попробую задачу для четверых

### ISSUE THREAD

**Issue by iwatkot** [iwatkot/issues#31]
Это описание тут типа. Descr edited

[link](google.com)
### header
_ITALIC_
**BOLD**
- [ ] 1
- [x] 2
- [ ] 3
- [x] 4

sample image
![Image](https://user-images.githubusercontent.com/16735312/227908598-e4d632c0-0784-439b-9bad-aac79003cd20.png)

code
```python
from ss import cuda
cuda.env.set('string')
print(f"{str(cuda)}_{1}_{2}")
```

- 1
- 2
- 3
- 4

1. a
2. b
3. c
4. d
5. f
6. e
7. r

@iwatkot 

issue #13 

| Header | Header |
|--------|--------|
| Cell | Cell |
| Cell | Cell |

**Comment by ruslantau** [comment]
test comm
